############# Externalized Configuration ##############
customer:
  service:
    name: customer-service
    port: 8082
    actuator:
      port: 9082
    logging:
      level:
        root: INFO
        spring: INFO
        flyway: INFO
        r2dbc: INFO
        netty: INFO
        reactor: INFO
        reactive: INFO
        webflux: INFO
        service: INFO
    defaultPageSize: 10
    exceptionNotFound: https://api.bookstore.com/errors/not-found
    exceptionGeneral: https://api.bookstore.com/errors/general
    exceptionBadRequest: https://api.bookstore.com/errors/bad-request

db:
  url:
    r2dbc: r2dbc:postgresql://localhost:5432/customer_db
    flyway: jdbc:postgresql://localhost:5432/customer_db
  username: user
  password: password

############# SPRING CONFIGURATION ###############

spring:
  application:
    name: ${customer.service.name:customer-service}
  r2dbc:
    url: ${db.url.r2dbc:r2dbc:postgresql://localhost:5432/customer_db}
    username: ${db.username:user}
    password: ${db.password:password}
    pool:
      max-size: 10
      initial-size: 5
      max-create-connection-time: 2s
  flyway:
    url: ${db.url.flyway:jdbc:postgresql://localhost:5432/customer_db}
    user: ${db.username:user}
    password: ${db.password:password}
    enabled: true



  ############# SPRING CLOUD STREAM WITH KAFKA CONFIGURATION ###############
  cloud:
    function:
      definition: processor;customerEventProducer
    stream:
      default:
        producer:
          useNativeEncoding: true

      bindings:
        processor-in-0:
          destination: order-events
          group: "customer-service-group"
        processor-out-0:
          destination: customer-events
        customerEventProducer-out-0:
          destination: customer-events
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "spring.json.trusted.packages": "com.example.customer_service.events"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer

########### SERVER CONFIGURATION #############

server:
  port: ${customer.service.port:8082}
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

############ ACTUATOR CONFIGURATION #############
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  info:
    git:
      enabled: true
      mode: full
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: ${customer.service.actuator.port:9082}

############## LOGGING CONFIGURATION ################
logging:
  level:
    root: ${customer.service.logging.level.root:INFO}
    org.springframework: ${customer.service.logging.level.spring:INFO}
    org.springframework.web.reactive: ${customer.service.logging.level.reactive:INFO}
    org.springframework.web: ${customer.service.logging.level.webflux:INFO}
    io.netty: ${customer.service.logging.level.netty:INFO}
    io.r2dbc: ${customer.service.logging.level.r2dbc:INFO}
    org.flywaydb: ${customer.service.logging.level.flyway:INFO}
    reactor: ${customer.service.logging.level.reactor:INFO}
    com.example.customer_service: ${customer.service.logging.level.service:INFO}



