############# Externalized Configuration ##############
order:
  service:
    name: order-service
    port: 8082
    actuator:
      port: 9082
    logging:
      level:
        root: INFO
        spring: INFO
        flyway: INFO
        r2dbc: INFO
        netty: INFO
        reactor: INFO
        reactive: INFO
        webflux: INFO
        service: INFO
    defaultPageSize: 10
    exceptionNotFound: https://api.bookstore.com/errors/not-found
    exceptionGeneral: https://api.bookstore.com/errors/general

db:
  url:
    r2dbc: r2dbc:postgresql://localhost:5432/order_db
    flyway: jdbc:postgresql://localhost:5432/order_db
  username: user
  password: password


############# SPRING CONFIGURATION ###############

spring:
  application:
    name: ${order.service.name:order-service}

############## DATABASE CONFIGURATION ################
  r2dbc:
    url: ${db.url.r2dbc:r2dbc:postgresql://localhost:5432/order_db}
    username: ${db.username:user}
    password: ${db.password:password}
    pool:
      max-size: 10
      initial-size: 5
      max-create-connection-time: 2s
  flyway:
    url: ${db.url.flyway:jdbc:postgresql://localhost:5432/order_db}
    user: ${db.username:user}
    password: ${db.password:password}


############# KAFKA CONFIGURATION #############



########### SERVER CONFIGURATION #############

server:
  port: ${order.service.port:8082}
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

############ ACTUATOR CONFIGURATION #############
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  info:
    git:
      enabled: true
      mode: full
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: ${order.service.actuator.port:9082}

############## LOGGING CONFIGURATION ################
logging:
  level:
    root: ${order.service.logging.level.root:INFO}
    org.springframework: ${order.service.logging.level.spring:INFO}
    org.springframework.web.reactive: ${order.service.logging.level.reactive:INFO}
    org.springframework.web: ${order.service.logging.level.webflux:INFO}
    io.netty: ${order.service.logging.level.netty:INFO}
    io.r2dbc: ${order.service.logging.level.r2dbc:INFO}
    org.flywaydb: ${order.service.logging.level.flyway:INFO}
    reactor: ${order.service.logging.level.reactor:INFO}
    com.example.catalog_service: ${order.service.logging.level.service:INFO}




