name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'

      - name: Apply Spotless
        run: |
          cd catalog-service  # Navigate to the catalog-service directory
          mvn spotless:apply  # Run the Spotless apply command

      - name: Build with Maven
        run: |
          cd catalog-service  # Navigate to the catalog-service directory
          mvn -ntp verify     # Run the Maven build
