name: Order Service

on:
  push:
    paths:
      - order-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'

      - name: Apply Spotless
        run: |
          cd order-service  # Navigate to the order-service directory
          mvn spotless:apply  # Run the Spotless apply command

      - name: Build with Maven
        env:
          TEST_TIMEOUT: 60000  # Set the test timeout property
        run: |
          cd order-service  # Navigate to the order-service directory
          mvn -ntp verify     # Run the Maven build

      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        if: success()
        run: |
          cd order-service  # Navigate to the order-service directory
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-order-service .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-order-service